Feat creating day all page and getting comment data in detail page
yuki-o1o5/Hacker-News-in-Japanese pull request #23
Opened 2022-12-13 12:11 UTC by yuki-o1o5

## Proposed Changes
Update main/index.jsx and main/[id].jsx
Update All/index.jsx and All/[id].jsx

#### Code changes and Reasons
- Add a link in order to go to main/[id] page from main page
- Change Article number in main page in order to increase the number automatically  
- Add comment out all components in order to let GitHub know differences between uppercase and lowercase 
- Add populateGiftConfigurationParameters function to populate data
- Create some components in order to use all page and all/[id] page
- Create all page and all/[id] page and refactor them in order to use getStaticProps and getStaticPath

#### Related Issues
- #4 
- #8 
- #11 
- #13 
- #14  
- #16 

## Additional Info
In order to get the newest top 3ids, please pass the following URL in the API platform and use it instead of [id]
`https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty&limitToFirst=3&orderBy="$key"`
http://localhost:3000/main/[id]
http://localhost:3000/all/[id]

2022-12-14 09:34 UTC, yuyaohshimo requested changes
Can you add a screencast so that I can check the screens and behavior?

2022-12-14 09:34 UTC, yuyaohshimo commented on pages/all/[id].jsx
> +      "https://hacker-news.firebaseio.com/v0/item/" +
minor: You should use template literals because it is easy to understand.

2022-12-14 09:34 UTC, yuyaohshimo commented on pages/all/[id].jsx
> +  const topCommentReplies = await Promise.all(
You should add null checker for `topComment.kids` before running `Promise.all`.

2022-12-16 00:52 UTC, yuki-o1o5 commented on pages/all/[id].jsx
> +      "https://hacker-news.firebaseio.com/v0/item/" +
I understand. I changed it to template literals.
 --> [link1](https://github.com/yuki-o1o5/Hacker-News-in-Japanese/commit/3876ce96a795528ac285f8935e62166b9f8b76bd)
 --> [link2](https://github.com/yuki-o1o5/Hacker-News-in-Japanese/commit/624266427ed7ac66bb6b70c2c76a408a8476eb15)

2022-12-17 07:52 UTC, yuyaohshimo commented on pages/all/[id].jsx
> +      "https://hacker-news.firebaseio.com/v0/item/" +
GJ!

2022-12-17 08:18 UTC, yuyaohshimo commented on pages/all/[id].jsx
> +  const topComment = story.kids ? await getCommentUrl(story.kids[0]) : "";
I think the following code is easy to understand more to check `undefined`:

```javascript

const topComment = story.kids ? await getCommentUrl(story.kids[0]) : "";

let topCommentReplies = [];
if (!topComment.kids) {
  topCommentReplies = await Promise.all(
    topComment.kids.map((topCommentKid) => getCommentUrl(topCommentKid))
  );
}
```

2022-12-17 23:08 UTC, yuki-o1o5 commented on pages/all/[id].jsx
> +  const topComment = story.kids ? await getCommentUrl(story.kids[0]) : "";
I understand. I changed the upper code. --> [link](https://github.com/yuki-o1o5/Hacker-News-in-Japanese/commit/29822635d7e040767a2da2534576f8bc79d9f399)

2022-12-20 09:10 UTC, merged